// Asset manifest. Gameplay refers to ids only; this table says how each id looks.
//   model         Qt Quick 3D QML produced by balsam from the QtMeshEditor GLB (scripts/import-runtime.py)
//   representation "model" | "placeholder" - what the game shows for this id right now
//   height        metres the model should stand tall in the scene (TRELLIS.2 output is a ~1 unit box)
//   footOffset    model units from origin down to the base (lifts it to y = 0), unitHeight = model bbox height
//   rotation      yaw degrees so the model faces +Z at rest (TRELLIS.2 output faces -Z)
//   placeholder   what to draw when no model is available: toon boxes { shape, color, accent }
//   status        "generated" | "pending" | "placeholder"
//   tint          optional colour multiplied into the model (the human electrician reuses the zombie model)
// scripts/update-asset-manifest.py fills in model/unitHeight/footOffset/status after an import.
.pragma library

var assets = {
    // characters (rigged: Idle / Walk / Bite clips)
    zombie_standard:    { unitDepth: 0.243, unitWidth: 0.93, footOffset: 0.511, unitHeight: 1.023, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_standard/PropZombieStandard.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#3f8f8a", accent: "#7fc27a" } },
    zombie_janitor:     { unitDepth: 0.233, unitWidth: 1.023, footOffset: 0.511, unitHeight: 1.023, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_janitor/PropZombieJanitor.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#33456e", accent: "#8fb36f" } },
    zombie_electrician: { unitDepth: 0.209, unitWidth: 0.778, footOffset: 0.512, unitHeight: 1.022, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_electrician/PropZombieElectrician.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#2e3b63", accent: "#d8e63a" } },
    zombie_brute:       { unitDepth: 0.286, unitWidth: 1.023, footOffset: 0.387, unitHeight: 0.774, height: 2.05, rotation: 180, model: "../assets/runtime/zombie_brute/PropZombieBrute.qml", representation: "model", status: "generated", placeholder: { shape: "brute", color: "#6b7d3b", accent: "#e8792c" } },
    guard:              { unitDepth: 0.227, unitWidth: 0.928, footOffset: 0.511, unitHeight: 1.023, height: 1.85, rotation: 180, model: "../assets/runtime/guard/PropGuard.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#1f2f5e", accent: "#f0d2b6" } },
    nurse:              { unitDepth: 0.214, unitWidth: 0.883, footOffset: 0.511, unitHeight: 1.022, height: 1.70, rotation: 180, model: "../assets/runtime/nurse/PropNurse.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#6fa3e6", accent: "#f0d2b6" } },
    electrician_human:  { unitDepth: 0.208, unitWidth: 1.023, footOffset: 0.486, unitHeight: 0.971, height: 1.75, rotation: 180, model: "../assets/runtime/electrician_human/PropElectricianHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#2e3b63", accent: "#f0d2b6" } },
    // props
    laser_pillar:       { unitDepth: 0.539, unitWidth: 0.537, footOffset: 0.51, unitHeight: 1.02, height: 1.4, rotation: 225, model: "../assets/runtime/laser_pillar/PropLaserPillar.qml", representation: "model", status: "generated", placeholder: { shape: "pillar", color: "#f2b81f", accent: "#2b2b2b" } },
    security_camera:    { unitDepth: 0.562, unitWidth: 1.024, footOffset: 0.447, unitHeight: 0.895, height: 0.35, rotation: 270, model: "../assets/runtime/security_camera/PropSecurityCamera.qml", representation: "model", status: "generated", placeholder: { shape: "camera", color: "#e9eef5", accent: "#1c1f27" } },
    electrical_panel:   { unitDepth: 0.402, unitWidth: 0.896, footOffset: 0.51, unitHeight: 1.021, height: 1.0, rotation: 170, model: "../assets/runtime/electrical_panel/PropElectricalPanel.qml", representation: "model", status: "generated", placeholder: { shape: "panel", color: "#9aa3ad", accent: "#f2c02f" } },
    maintenance_door:   { unitDepth: 0.226, unitWidth: 0.732, footOffset: 0.512, unitHeight: 1.024, height: 2.1, rotation: 170, model: "../assets/runtime/maintenance_door/PropMaintenanceDoor.qml", representation: "model", status: "generated", placeholder: { shape: "door", color: "#2f8f8a", accent: "#f2c02f" } },
    medical_cart:       { unitDepth: 0.81, unitWidth: 0.841, footOffset: 0.512, unitHeight: 1.024, height: 1.0, rotation: 180, model: "../assets/runtime/medical_cart/PropMedicalCart.qml", representation: "model", status: "generated", placeholder: { shape: "cart", color: "#3ba39a", accent: "#e9eef5" } },
    radio:              { unitDepth: 0.458, unitWidth: 1.023, footOffset: 0.421, unitHeight: 0.844, height: 0.32, rotation: 180, model: "../assets/runtime/radio/PropRadio.qml", representation: "model", status: "generated", placeholder: { shape: "box", color: "#2f8f8a", accent: "#e9dcc0" } },
    locker:             { unitDepth: 0.339, unitWidth: 0.312, footOffset: 0.511, unitHeight: 1.023, height: 1.9, rotation: 180, model: "../assets/runtime/locker/PropLocker.qml", representation: "model", status: "generated", placeholder: { shape: "locker", color: "#5b8fc9", accent: "#3a3f4a" } },
    brain_jar:          { unitDepth: 0.757, unitWidth: 0.755, footOffset: 0.511, unitHeight: 1.023, height: 0.5, rotation: 180, model: "../assets/runtime/brain_jar/PropBrainJar.qml", representation: "model", status: "generated", placeholder: { shape: "jar", color: "#3a6b63", accent: "#f2a0b8" } },
    curtain_screen:     { unitDepth: 0.858, unitWidth: 0.99, footOffset: 0.511, unitHeight: 1.018, height: 1.8, rotation: 180, model: "../assets/runtime/curtain_screen/PropCurtainScreen.qml", representation: "model", status: "generated", placeholder: { shape: "curtain", color: "#8fb6e6", accent: "#3a8f7a" } },
    hospital_bed:       { unitDepth: 0.585, unitWidth: 1.021, footOffset: 0.277, unitHeight: 0.556, height: 0.95, rotation: 90, model: "../assets/runtime/hospital_bed/PropHospitalBed.qml", representation: "model", status: "generated", placeholder: { shape: "bed", color: "#e6e2d6", accent: "#8fb6e6" } },
    hospital_bed_modern:{ unitDepth: 0.533, unitWidth: 1.023, footOffset: 0.26, unitHeight: 0.522, height: 0.95, rotation: 90, model: "../assets/runtime/hospital_bed_modern/PropHospitalBedModern.qml", representation: "model", status: "generated", placeholder: { shape: "bed", color: "#e9eef5", accent: "#5b8fc9" } },
    curtain_divider:    { unitDepth: 1.003, unitWidth: 0.742, footOffset: 0.51, unitHeight: 1.004, height: 1.8, rotation: 285, model: "../assets/runtime/curtain_divider/PropCurtainDivider.qml", representation: "model", status: "generated", placeholder: { shape: "curtain", color: "#8fb6e6", accent: "#3a8f7a" } },
    hospital_building:  { unitDepth: 0.733, unitWidth: 1.023, footOffset: 0.248, unitHeight: 0.495, height: 6.0, rotation: 180, model: "../assets/runtime/hospital_building/PropHospitalBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "box", color: "#e9eef5", accent: "#2f8f8a" } },
    ambulance:          { unitDepth: 1.023, unitWidth: 0.581, footOffset: 0.288, unitHeight: 0.582, height: 2.3, rotation: 268, model: "../assets/runtime/ambulance/PropAmbulance.qml", representation: "model", status: "generated", placeholder: { shape: "ambulance", color: "#f4f4f4", accent: "#d9403a" } },
    hospital_door:      { unitDepth: 0.164, unitWidth: 0.62, footOffset: 0.511, unitHeight: 1.023, height: 2.1, rotation: 180, model: "../assets/runtime/hospital_door/PropHospitalDoor.qml", representation: "model", status: "generated", placeholder: { shape: "door", color: "#e9e4d8", accent: "#3a8f8a" } },
    wheelchair:         { unitDepth: 1.023, unitWidth: 0.758, footOffset: 0.441, unitHeight: 0.886, height: 0.95, rotation: 180, model: "../assets/runtime/wheelchair/PropWheelchair.qml", representation: "model", status: "generated", placeholder: { shape: "cart", color: "#3ba39a", accent: "#2b3a5e" } },
    iv_stand:           { unitDepth: 0.517, unitWidth: 0.502, footOffset: 0.511, unitHeight: 1.022, height: 1.7, rotation: 180, model: "../assets/runtime/iv_stand/PropIvStand.qml", representation: "model", status: "generated", placeholder: { shape: "pillar", color: "#9aa3ad", accent: "#3ba39a" } },
    vending_machine:    { unitDepth: 0.442, unitWidth: 0.737, footOffset: 0.512, unitHeight: 1.024, height: 1.9, rotation: 180, model: "../assets/runtime/vending_machine/PropVendingMachine.qml", representation: "model", status: "generated", placeholder: { shape: "locker", color: "#3ba39a", accent: "#e9dcc0" } },
    // roster zombies + their human versions (rigged: Idle / Walk / Run / Bite)
    zombie_nurse:           { unitDepth: 0.21, unitWidth: 0.951, footOffset: 0.511, unitHeight: 1.023, height: 1.70, rotation: 180, model: "../assets/runtime/zombie_nurse/PropZombieNurse.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#6fa3e6", accent: "#8fd48a" } },
    zombie_doctor:          { unitDepth: 0.206, unitWidth: 1.024, footOffset: 0.463, unitHeight: 0.897, height: 1.80, rotation: 180, model: "../assets/runtime/zombie_doctor/PropZombieDoctor.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#f0f0f0", accent: "#8fd48a" } },
    zombie_security_guard:  { unitDepth: 0.234, unitWidth: 1.024, footOffset: 0.424, unitHeight: 0.847, height: 1.85, rotation: 180, model: "../assets/runtime/zombie_security_guard/PropZombieSecurityGuard.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#1f2f5e", accent: "#8fd48a" } },
    zombie_chef:            { unitDepth: 0.225, unitWidth: 0.872, footOffset: 0.512, unitHeight: 1.023, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_chef/PropZombieChef.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#f0f0f0", accent: "#8fd48a" } },
    zombie_child:           { unitDepth: 0.383, unitWidth: 1.023, footOffset: 0.488, unitHeight: 0.974, height: 1.30, rotation: 180, model: "../assets/runtime/zombie_child/PropZombieChild.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#f2c02f", accent: "#8fd48a" } },
    zombie_firefighter:     { unitDepth: 0.226, unitWidth: 1.022, footOffset: 0.451, unitHeight: 0.901, height: 1.85, rotation: 180, model: "../assets/runtime/zombie_firefighter/PropZombieFirefighter.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#c8a35a", accent: "#8fd48a" } },
    zombie_athlete:         { unitDepth: 0.264, unitWidth: 0.892, footOffset: 0.512, unitHeight: 1.023, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_athlete/PropZombieAthlete.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#6a4fb3", accent: "#8fd48a" } },
    zombie_office_worker:   { unitDepth: 0.224, unitWidth: 1.024, footOffset: 0.493, unitHeight: 0.987, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_office_worker/PropZombieOfficeWorker.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#e9e4d8", accent: "#8fd48a" } },
    zombie_screamer:        { unitDepth: 0.17, unitWidth: 0.796, footOffset: 0.509, unitHeight: 1.018, height: 1.75, rotation: 180, model: "../assets/runtime/zombie_screamer/PropZombieScreamer.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#9b59b6", accent: "#8fd48a" } },
    doctor_human:           { unitDepth: 0.21, unitWidth: 1.023, footOffset: 0.461, unitHeight: 0.921, height: 1.80, rotation: 180, model: "../assets/runtime/doctor_human/PropDoctorHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#f0f0f0", accent: "#f0d2b6" } },
    chef_human:             { unitDepth: 0.221, unitWidth: 1.023, footOffset: 0.443, unitHeight: 0.886, height: 1.75, rotation: 180, model: "../assets/runtime/chef_human/PropChefHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#f0f0f0", accent: "#f0d2b6" } },
    child_human:            { unitDepth: 0.381, unitWidth: 1.024, footOffset: 0.497, unitHeight: 0.973, height: 1.30, rotation: 180, model: "../assets/runtime/child_human/PropChildHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#f2c02f", accent: "#f0d2b6" } },
    athlete_human:          { unitDepth: 0.271, unitWidth: 0.88, footOffset: 0.511, unitHeight: 1.023, height: 1.75, rotation: 180, model: "../assets/runtime/athlete_human/PropAthleteHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#6a4fb3", accent: "#f0d2b6" } },
    firefighter_human:      { unitDepth: 0.22, unitWidth: 1.022, footOffset: 0.476, unitHeight: 0.921, height: 1.85, rotation: 180, model: "../assets/runtime/firefighter_human/PropFirefighterHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#c8a35a", accent: "#f0d2b6" } },
    office_worker_human:    { unitDepth: 0.221, unitWidth: 0.943, footOffset: 0.511, unitHeight: 1.023, height: 1.75, rotation: 180, model: "../assets/runtime/office_worker_human/PropOfficeWorkerHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#e9e4d8", accent: "#f0d2b6" } },
    screamer_human:         { unitDepth: 0.177, unitWidth: 1.024, footOffset: 0.487, unitHeight: 0.973, height: 1.75, rotation: 180, model: "../assets/runtime/screamer_human/PropScreamerHuman.qml", representation: "model", status: "generated", placeholder: { shape: "person", color: "#9b59b6", accent: "#f0d2b6" } },
    // PLACEHOLDER: no concept art for the guard dog or the food bait yet
    dog:                    { height: 0.7, rotation: 0, model: "", representation: "placeholder", status: "placeholder", placeholder: { shape: "dog", color: "#8a6a3f", accent: "#5e4526" } },
    bait:                   { height: 0.3, rotation: 0, model: "", representation: "placeholder", status: "placeholder", placeholder: { shape: "food", color: "#e0742f", accent: "#f2c02f" } },
    // campaign locations and props (generated from docs/concept, batch 4)
    mall_building:      { unitDepth: 1.021, unitWidth: 1.021, footOffset: 0.169, unitHeight: 0.337, height: 6.0, rotation: 180, model: "../assets/runtime/mall_building/PropMallBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#e9e4d8", accent: "#3a8f8a" } },
    storefront:         { unitDepth: 0.487, unitWidth: 1.024, footOffset: 0.235, unitHeight: 0.471, height: 3.5, rotation: 180, model: "../assets/runtime/storefront/PropStorefront.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#3a8f8a", accent: "#f2c02f", w: 4, d: 1 } },
    dock_shutter:       { unitDepth: 0.468, unitWidth: 1.024, footOffset: 0.4, unitHeight: 0.809, height: 2.6, rotation: 180, model: "../assets/runtime/dock_shutter/PropDockShutter.qml", representation: "model", status: "generated", placeholder: { shape: "shutter", color: "#9aa3ad", accent: "#f2c02f" } },
    security_gate:      { unitDepth: 0.796, unitWidth: 1.024, footOffset: 0.326, unitHeight: 0.652, height: 2.1, rotation: 180, model: "../assets/runtime/security_gate/PropSecurityGate.qml", representation: "model", status: "generated", placeholder: { shape: "gate", color: "#9aa3ad", accent: "#3a8f8a" } },
    food_court_table:   { unitDepth: 1.023, unitWidth: 1.023, footOffset: 0.238, unitHeight: 0.477, height: 0.8, rotation: 180, model: "../assets/runtime/food_court_table/PropFoodCourtTable.qml", representation: "model", status: "generated", placeholder: { shape: "table", color: "#e9e4d8", accent: "#3a8f8a" } },
    school_building:    { unitDepth: 1.022, unitWidth: 0.929, footOffset: 0.178, unitHeight: 0.355, height: 6.0, rotation: 180, model: "../assets/runtime/school_building/PropSchoolBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#f2d47a", accent: "#3a8f8a" } },
    school_desk:        { unitDepth: 0.825, unitWidth: 1.022, footOffset: 0.429, unitHeight: 0.857, height: 0.8, rotation: 180, model: "../assets/runtime/school_desk/PropSchoolDesk.qml", representation: "model", status: "generated", placeholder: { shape: "desk", color: "#d9a066", accent: "#3a8f8a" } },
    school_lockers:     { unitDepth: 0.305, unitWidth: 1.024, footOffset: 0.312, unitHeight: 0.621, height: 1.9, rotation: 180, model: "../assets/runtime/school_lockers/PropSchoolLockers.qml", representation: "model", status: "generated", placeholder: { shape: "locker", color: "#f2c02f", accent: "#3a8f8a" } },
    vent_hatch:         { unitDepth: 1.023, unitWidth: 0.934, footOffset: 0.252, unitHeight: 0.503, height: 0.9, rotation: 180, model: "../assets/runtime/vent_hatch/PropVentHatch.qml", representation: "model", status: "generated", placeholder: { shape: "hatch", color: "#9aa3ad", accent: "#2b3a5e" } },
    gym_bleachers:      { unitDepth: 1.023, unitWidth: 0.62, footOffset: 0.257, unitHeight: 0.513, height: 1.2, rotation: 90, model: "../assets/runtime/gym_bleachers/PropGymBleachers.qml", representation: "model", status: "generated", placeholder: { shape: "box", color: "#3a8f8a", accent: "#e9e4d8", w: 3, d: 1.5 } },
    office_building:    { unitDepth: 0.934, unitWidth: 1.023, footOffset: 0.369, unitHeight: 0.732, height: 8.0, rotation: 180, model: "../assets/runtime/office_building/PropOfficeBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#e9e4d8", accent: "#5b8fc9" } },
    office_cubicle:     { unitDepth: 1.023, unitWidth: 1.006, footOffset: 0.354, unitHeight: 0.708, height: 1.5, rotation: 180, model: "../assets/runtime/office_cubicle/PropOfficeCubicle.qml", representation: "model", status: "generated", placeholder: { shape: "desk", color: "#3a8f8a", accent: "#e9e4d8" } },
    server_rack:        { unitDepth: 0.542, unitWidth: 0.642, footOffset: 0.512, unitHeight: 1.023, height: 2.0, rotation: 180, model: "../assets/runtime/server_rack/PropServerRack.qml", representation: "model", status: "generated", placeholder: { shape: "locker", color: "#2b3a5e", accent: "#49e06a" } },
    meeting_table:      { unitDepth: 0.907, unitWidth: 1.022, footOffset: 0.168, unitHeight: 0.336, height: 0.8, rotation: 180, model: "../assets/runtime/meeting_table/PropMeetingTable.qml", representation: "model", status: "generated", placeholder: { shape: "table", color: "#e9e4d8", accent: "#3a8f8a", w: 2.4, d: 1.2 } },
    elevator:           { unitDepth: 0.479, unitWidth: 1.023, footOffset: 0.462, unitHeight: 0.924, height: 2.4, rotation: 180, model: "../assets/runtime/elevator/PropElevator.qml", representation: "model", status: "generated", placeholder: { shape: "door", color: "#9aa3ad", accent: "#3a8f8a" } },
    reception_desk:     { unitDepth: 0.488, unitWidth: 1.023, footOffset: 0.181, unitHeight: 0.361, height: 1.1, rotation: 180, model: "../assets/runtime/reception_desk/PropReceptionDesk.qml", representation: "model", status: "generated", placeholder: { shape: "console", color: "#e9e4d8", accent: "#f2c02f", w: 2.6 } },
    firehouse_building: { unitDepth: 0.736, unitWidth: 1.023, footOffset: 0.302, unitHeight: 0.601, height: 6.0, rotation: 180, model: "../assets/runtime/firehouse_building/PropFirehouseBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#d9403a", accent: "#e9e4d8" } },
    fire_engine:        { unitDepth: 1.022, unitWidth: 0.451, footOffset: 0.251, unitHeight: 0.507, height: 3.0, rotation: 180, model: "../assets/runtime/fire_engine/PropFireEngine.qml", representation: "model", status: "generated", placeholder: { shape: "truck", color: "#d9403a", accent: "#e9e4d8" } },
    fire_valve:         { unitDepth: 1.022, unitWidth: 0.369, footOffset: 0.308, unitHeight: 0.618, height: 1.1, rotation: 180, model: "../assets/runtime/fire_valve/PropFireValve.qml", representation: "model", status: "generated", placeholder: { shape: "jar", color: "#3a8f8a", accent: "#d9403a" } },
    vent_fan:           { height: 1.6, rotation: 180, model: "", representation: "placeholder", status: "pending", placeholder: { shape: "box", color: "#3a8f8a", accent: "#9aa3ad", w: 1.4, d: 0.8 } },
    gear_rack:          { unitDepth: 0.414, unitWidth: 1.022, footOffset: 0.426, unitHeight: 0.852, height: 1.9, rotation: 180, model: "../assets/runtime/gear_rack/PropGearRack.qml", representation: "model", status: "generated", placeholder: { shape: "locker", color: "#d9403a", accent: "#f2c02f" } },
    studio_building:    { unitDepth: 1.022, unitWidth: 0.928, footOffset: 0.273, unitHeight: 0.559, height: 6.0, rotation: 180, model: "../assets/runtime/studio_building/PropStudioBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#e9e4d8", accent: "#d9403a" } },
    studio_camera:      { unitDepth: 0.889, unitWidth: 0.577, footOffset: 0.508, unitHeight: 1.019, height: 1.6, rotation: 180, model: "../assets/runtime/studio_camera/PropStudioCamera.qml", representation: "model", status: "generated", placeholder: { shape: "camera", color: "#e9e4d8", accent: "#1c1f27" } },
    control_console:    { unitDepth: 0.521, unitWidth: 1.024, footOffset: 0.265, unitHeight: 0.53, height: 1.2, rotation: 180, model: "../assets/runtime/control_console/PropControlConsole.qml", representation: "model", status: "generated", placeholder: { shape: "console", color: "#e9e4d8", accent: "#5aa8ff", w: 3 } },
    stage_lights:       { unitDepth: 0.349, unitWidth: 1.018, footOffset: 0.279, unitHeight: 0.562, height: 2.8, rotation: 180, model: "../assets/runtime/stage_lights/PropStageLights.qml", representation: "model", status: "generated", placeholder: { shape: "pillar", color: "#2b3a5e", accent: "#f2c02f" } },
    lab_building:       { unitDepth: 1.013, unitWidth: 1.023, footOffset: 0.205, unitHeight: 0.409, height: 6.0, rotation: 180, model: "../assets/runtime/lab_building/PropLabBuilding.qml", representation: "model", status: "generated", placeholder: { shape: "building", color: "#e9e4d8", accent: "#7fe07a" } },
    containment_cell:   { unitDepth: 0.892, unitWidth: 1.003, footOffset: 0.509, unitHeight: 1.021, height: 2.4, rotation: 180, model: "../assets/runtime/containment_cell/PropContainmentCell.qml", representation: "model", status: "generated", placeholder: { shape: "cell", color: "#3a8f8a", accent: "#bfe8ff" } },
    med_scanner:        { unitDepth: 0.77, unitWidth: 1.023, footOffset: 0.303, unitHeight: 0.598, height: 1.6, rotation: 90, model: "../assets/runtime/med_scanner/PropMedScanner.qml", representation: "model", status: "generated", placeholder: { shape: "bed", color: "#e9e4d8", accent: "#3a8f8a" } },
    lab_console:        { unitDepth: 0.674, unitWidth: 1.024, footOffset: 0.329, unitHeight: 0.658, height: 1.2, rotation: 180, model: "../assets/runtime/lab_console/PropLabConsole.qml", representation: "model", status: "generated", placeholder: { shape: "console", color: "#e9e4d8", accent: "#7fe07a", w: 2 } },
    specimen_tank:      { unitDepth: 0.754, unitWidth: 0.882, footOffset: 0.512, unitHeight: 1.023, height: 1.8, rotation: 180, model: "../assets/runtime/specimen_tank/PropSpecimenTank.qml", representation: "model", status: "generated", placeholder: { shape: "jar", color: "#3a8f8a", accent: "#7fff7a" } }
}

function get(id) { return assets[id] || null }
